export enum Role {
    SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
    ADMIN = 'ROLE_ADMIN',
    MANAGER = 'ROLE_MANAGER',
    USER = 'ROLE_USER',
    HR = 'ROLE_HR',
    ROLE_ADMIN = "ROLE_ADMIN",
    ROLE_MANAGER = "ROLE_MANAGER",
    ROLE_ANALYST = "ROLE_ANALYST",
    ROLE_SALESMAN = "ROLE_SALESMAN"
  }
  